name: Smoke test

on: ['workflow_dispatch']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v6
    - uses: actions/setup-node@v7
      with:
        node-version: 22
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: ln -s .. node_modules/eslint-plugin-knex
    - run: pnpm test:smoke
      env:
        CI: true
